# This describes a self-contained demo of RAIS, using nginx to serve up the
# static pages.  This isn't a production configuration file!!
#
# If you don't set up an override file (compose.override-example.yml,
# for instance), this will just use the stable version of RAIS from dockerhub.
#
# Put JP2s into docker/images and the apache entrypoint script will add them to
# the images served by from RAIS.
services:
  rais:
    image: uolibraries/rais
    environment:
      - URL
      - RAIS_ADDRESS
      - RAIS_LOGLEVEL
      - RAIS_TILEPATH=/var/local/images
      - RAIS_IIIFWEBPATH
      - RAIS_IIIFBASEURL
      - RAIS_INFOCACHELEN
      - RAIS_TILECACHELEN
      - RAIS_IMAGEMAXAREA
      - RAIS_IMAGEMAXWIDTH
      - RAIS_IMAGEMAXHEIGHT
      - RAIS_PLUGINS=*
      - RAIS_JPGQUALITY
      - RAIS_ALLOW_INSECURE_PLUGINS=0
    volumes:
      - ./docker/images:/var/local/images:ro
      - ./rais-example.toml:/etc/rais-template.toml:ro
      - ./cap-max.toml:/etc/rais-capabilities.toml:ro
      - ./docker/demo-rais-entry.sh:/entrypoint.sh:ro
    entrypoint: /entrypoint.sh

  web:
    image: nginx:1.15
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docker/images:/var/local/images:ro
      - ./docker/static:/static:ro
      - ./docker/demo-web-entry.sh:/entrypoint.sh:ro
    entrypoint: /entrypoint.sh
    depends_on:
      - rais
    ports:
      - 80:80
