# This produces a reasonably small production image for RAIS.  You may find it
# helpful to use the build image (Dockerfile.build) to produce the necessary
# binary.
FROM fedora:27
MAINTAINER Jeremy Echols <jechols@uoregon.edu>

# Install the runtime dependencies
RUN dnf install -y openjpeg2
RUN dnf install -y ImageMagick

ENV RAIS_TILEPATH /var/local/images
EXPOSE 12415

COPY bin/rais-server /opt/rais/rais-server
ENTRYPOINT /opt/rais/rais-server
