FROM golang:1-alpine AS build

RUN apk update && apk upgrade
RUN apk add git upx

RUN go install github.com/minio/minio@latest
RUN upx /go/bin/minio

FROM alpine:latest AS server

COPY --from=build /go/bin/minio /usr/local/bin/minio
